version: "3.8"

services:
  backend:
    build: ./quizapp-backend
    container_name: quizapp-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:

      #******************************************IMPORTANT*********************************************
      #dir had lien bach nkhdmo bnafss data (Cluster0) : 
      # LIEN = mongodb+srv://no3mane:Cf5pXW1LROe5z8n0@cluster0.jdjshgx.mongodb.net/quizapp?retryWrites=true&w=majority&appName=Cluster0

      - SPRING_DATA_MONGODB_URI=mongodb+srv://sami:GK0N8o2x0GjSamYX@cluster0.jdjshgx.mongodb.net/quizapp?retryWrites=true&w=majority&appName=Cluster0
      - SPRING_DATA_MONGODB_DATABASE=quizapp
      - JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

  frontend:
    build: ./quizapp-frontend
    container_name: quizapp-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:

