version: "3.8"

services:
  backend:
    build: ./quizapp-backend
    container_name: quizapp-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:

      - SPRING_DATA_MONGODB_URI=mongodb+srv://noamanehaimoudi79:12345678s@quizapp.p1xjaxb.mongodb.net/quizapp?retryWrites=true&w=majority&appName=quizapp
      - SPRING_DATA_MONGODB_DATABASE=quizapp

  frontend:
    build: ./quizapp-frontend
    container_name: quizapp-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
