version: "3.8"

services:
  backend:
    build: ./quizapp-backend
    container_name: quizapp-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://guess:0aGRADHax24DXzCL@cluster0.wgaas.mongodb.net/portfolio
      - SPRING_DATA_MONGODB_DATABASE=quizapp

  frontend:
    build: ./quizapp-frontend
    container_name: quizapp-frontend
    ports:
      - "3000:80"  # Vite sera buildé en production, servi avec nginx par exemple
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
